//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankView
    {
        public string AuctionName { get; set; }
        public string AuctionDescription { get; set; }
        public string AuctionToName { get; set; }
        public string AuctionToMobilePhone { get; set; }
        public int BankId { get; set; }
        public int PersonId { get; set; }
        public int AuctionId { get; set; }
        public decimal Bank { get; set; }
    }
}
