//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BidView
    {
        public string BidderName { get; set; }
        public string BidderMobilePhone { get; set; }
        public string AuctionItemDescription { get; set; }
        public string AuctionItemName { get; set; }
        public string AuctionItemTypeName { get; set; }
        public int AuctionId { get; set; }
        public string AuctionDescription { get; set; }
        public string AuctionName { get; set; }
        public bool AuctionActive { get; set; }
        public int BidId { get; set; }
        public int PersonId { get; set; }
        public int AuctionItemId { get; set; }
        public decimal BidAmount { get; set; }
    }
}
